# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cloudcheckr_cmx_client
from cloudcheckr_cmx_client.api.aws_credentials_api import AWSCredentialsApi  # noqa: E501
from cloudcheckr_cmx_client.rest import ApiException


class TestAWSCredentialsApi(unittest.TestCase):
    """AWSCredentialsApi unit test stubs"""

    def setUp(self):
        self.api = AWSCredentialsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_aws_external_id(self):
        """Test case for get_aws_external_id

        Get the external ID to use when creating an AWS cross-account role.  # noqa: E501
        """
        pass

    def test_modify_credential(self):
        """Test case for modify_credential

        Modify the credential on the account.  # noqa: E501
        """
        pass

    def test_modify_customer_aws_assume_role_credential(self):
        """Test case for modify_customer_aws_assume_role_credential

        Set the credential to use when assuming a cross-acount role.  # noqa: E501
        """
        pass

    def test_modify_default_credential(self):
        """Test case for modify_default_credential

        Modify the default credential on the account.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
