# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cloudcheckr_cmx_client
from cloudcheckr_cmx_client.api.azure_credentials_api import AzureCredentialsApi  # noqa: E501
from cloudcheckr_cmx_client.rest import ApiException


class TestAzureCredentialsApi(unittest.TestCase):
    """AzureCredentialsApi unit test stubs"""

    def setUp(self):
        self.api = AzureCredentialsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_modify_azure_enterprise_agreement_credentials(self):
        """Test case for modify_azure_enterprise_agreement_credentials

        Modify the credentials on the account.  # noqa: E501
        """
        pass

    def test_modify_azure_subscription_credentials(self):
        """Test case for modify_azure_subscription_credentials

        Modify the credentials on the account.  # noqa: E501
        """
        pass

    def test_request_csp_authorization(self):
        """Test case for request_csp_authorization

        Start the Azure CSP authorization consent flow.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
