# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cloudcheckr_cmx_client
from cloudcheckr_cmx_client.api.credentials_api import CredentialsApi  # noqa: E501
from cloudcheckr_cmx_client.rest import ApiException


class TestCredentialsApi(unittest.TestCase):
    """CredentialsApi unit test stubs"""

    def setUp(self):
        self.api = CredentialsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_account_credentials(self):
        """Test case for get_account_credentials

        Get all credentials configured on the account.  # noqa: E501
        """
        pass

    def test_get_customer_credentials(self):
        """Test case for get_customer_credentials

        Get all credentials configured on the customer.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
