# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cloudcheckr_cmx_client
from cloudcheckr_cmx_client.models.update_request_azure_subscription_credential_request_model import UpdateRequestAzureSubscriptionCredentialRequestModel  # noqa: E501
from cloudcheckr_cmx_client.rest import ApiException


class TestUpdateRequestAzureSubscriptionCredentialRequestModel(unittest.TestCase):
    """UpdateRequestAzureSubscriptionCredentialRequestModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateRequestAzureSubscriptionCredentialRequestModel(self):
        """Test UpdateRequestAzureSubscriptionCredentialRequestModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudcheckr_cmx_client.models.update_request_azure_subscription_credential_request_model.UpdateRequestAzureSubscriptionCredentialRequestModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
