# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cloudcheckr_cmx_client
from cloudcheckr_cmx_client.api.user_level_access_api import UserLevelAccessApi  # noqa: E501
from cloudcheckr_cmx_client.rest import ApiException


class TestUserLevelAccessApi(unittest.TestCase):
    """UserLevelAccessApi unit test stubs"""

    def setUp(self):
        self.api = UserLevelAccessApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user_level_access(self):
        """Test case for get_user_level_access

        Get user-level access for a single user.  # noqa: E501
        """
        pass

    def test_update_user_level_access(self):
        """Test case for update_user_level_access

        Updates the user-level access for the given user.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
