# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import cloudcheckr_cmx_client
from cloudcheckr_cmx_client.models.update_request_azure_csp_authorization_request_model import UpdateRequestAzureCspAuthorizationRequestModel  # noqa: E501
from cloudcheckr_cmx_client.rest import ApiException


class TestUpdateRequestAzureCspAuthorizationRequestModel(unittest.TestCase):
    """UpdateRequestAzureCspAuthorizationRequestModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateRequestAzureCspAuthorizationRequestModel(self):
        """Test UpdateRequestAzureCspAuthorizationRequestModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudcheckr_cmx_client.models.update_request_azure_csp_authorization_request_model.UpdateRequestAzureCspAuthorizationRequestModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
