# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AzureBillingAccountResponseModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'billing_account_id': 'str',
        'billing_account_type': 'str',
        'display_id': 'str',
        'display_name': 'str'
    }

    attribute_map = {
        'billing_account_id': 'billingAccountId',
        'billing_account_type': 'billingAccountType',
        'display_id': 'displayId',
        'display_name': 'displayName'
    }

    def __init__(self, billing_account_id=None, billing_account_type=None, display_id=None, display_name=None):  # noqa: E501
        """AzureBillingAccountResponseModel - a model defined in Swagger"""  # noqa: E501
        self._billing_account_id = None
        self._billing_account_type = None
        self._display_id = None
        self._display_name = None
        self.discriminator = None
        if billing_account_id is not None:
            self.billing_account_id = billing_account_id
        if billing_account_type is not None:
            self.billing_account_type = billing_account_type
        if display_id is not None:
            self.display_id = display_id
        if display_name is not None:
            self.display_name = display_name

    @property
    def billing_account_id(self):
        """Gets the billing_account_id of this AzureBillingAccountResponseModel.  # noqa: E501

        The billing account ID.  # noqa: E501

        :return: The billing_account_id of this AzureBillingAccountResponseModel.  # noqa: E501
        :rtype: str
        """
        return self._billing_account_id

    @billing_account_id.setter
    def billing_account_id(self, billing_account_id):
        """Sets the billing_account_id of this AzureBillingAccountResponseModel.

        The billing account ID.  # noqa: E501

        :param billing_account_id: The billing_account_id of this AzureBillingAccountResponseModel.  # noqa: E501
        :type: str
        """

        self._billing_account_id = billing_account_id

    @property
    def billing_account_type(self):
        """Gets the billing_account_type of this AzureBillingAccountResponseModel.  # noqa: E501

        The billing account type.  # noqa: E501

        :return: The billing_account_type of this AzureBillingAccountResponseModel.  # noqa: E501
        :rtype: str
        """
        return self._billing_account_type

    @billing_account_type.setter
    def billing_account_type(self, billing_account_type):
        """Sets the billing_account_type of this AzureBillingAccountResponseModel.

        The billing account type.  # noqa: E501

        :param billing_account_type: The billing_account_type of this AzureBillingAccountResponseModel.  # noqa: E501
        :type: str
        """

        self._billing_account_type = billing_account_type

    @property
    def display_id(self):
        """Gets the display_id of this AzureBillingAccountResponseModel.  # noqa: E501

        The raw account name from Azure.  # noqa: E501

        :return: The display_id of this AzureBillingAccountResponseModel.  # noqa: E501
        :rtype: str
        """
        return self._display_id

    @display_id.setter
    def display_id(self, display_id):
        """Sets the display_id of this AzureBillingAccountResponseModel.

        The raw account name from Azure.  # noqa: E501

        :param display_id: The display_id of this AzureBillingAccountResponseModel.  # noqa: E501
        :type: str
        """

        self._display_id = display_id

    @property
    def display_name(self):
        """Gets the display_name of this AzureBillingAccountResponseModel.  # noqa: E501

        The display name for this billing account.  # noqa: E501

        :return: The display_name of this AzureBillingAccountResponseModel.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this AzureBillingAccountResponseModel.

        The display name for this billing account.  # noqa: E501

        :param display_name: The display_name of this AzureBillingAccountResponseModel.  # noqa: E501
        :type: str
        """

        self._display_name = display_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AzureBillingAccountResponseModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AzureBillingAccountResponseModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
