# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AzureCspAuthorizationRequestModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'purchase_model': 'str',
        'region_group': 'str'
    }

    attribute_map = {
        'purchase_model': 'purchaseModel',
        'region_group': 'regionGroup'
    }

    def __init__(self, purchase_model=None, region_group=None):  # noqa: E501
        """AzureCspAuthorizationRequestModel - a model defined in Swagger"""  # noqa: E501
        self._purchase_model = None
        self._region_group = None
        self.discriminator = None
        if purchase_model is not None:
            self.purchase_model = purchase_model
        if region_group is not None:
            self.region_group = region_group

    @property
    def purchase_model(self):
        """Gets the purchase_model of this AzureCspAuthorizationRequestModel.  # noqa: E501

        The account's purchase model.  # noqa: E501

        :return: The purchase_model of this AzureCspAuthorizationRequestModel.  # noqa: E501
        :rtype: str
        """
        return self._purchase_model

    @purchase_model.setter
    def purchase_model(self, purchase_model):
        """Sets the purchase_model of this AzureCspAuthorizationRequestModel.

        The account's purchase model.  # noqa: E501

        :param purchase_model: The purchase_model of this AzureCspAuthorizationRequestModel.  # noqa: E501
        :type: str
        """
        allowed_values = ["AzurePlan", "Classic"]  # noqa: E501
        if purchase_model not in allowed_values:
            raise ValueError(
                "Invalid value for `purchase_model` ({0}), must be one of {1}"  # noqa: E501
                .format(purchase_model, allowed_values)
            )

        self._purchase_model = purchase_model

    @property
    def region_group(self):
        """Gets the region_group of this AzureCspAuthorizationRequestModel.  # noqa: E501

        The account's region group (i.e. the unique data center group that is being used, e.g. commercial, gov, etc).  # noqa: E501

        :return: The region_group of this AzureCspAuthorizationRequestModel.  # noqa: E501
        :rtype: str
        """
        return self._region_group

    @region_group.setter
    def region_group(self, region_group):
        """Sets the region_group of this AzureCspAuthorizationRequestModel.

        The account's region group (i.e. the unique data center group that is being used, e.g. commercial, gov, etc).  # noqa: E501

        :param region_group: The region_group of this AzureCspAuthorizationRequestModel.  # noqa: E501
        :type: str
        """
        allowed_values = ["Commercial", "UsGov", "Germany"]  # noqa: E501
        if region_group not in allowed_values:
            raise ValueError(
                "Invalid value for `region_group` ({0}), must be one of {1}"  # noqa: E501
                .format(region_group, allowed_values)
            )

        self._region_group = region_group

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AzureCspAuthorizationRequestModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AzureCspAuthorizationRequestModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
