# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CustomerPlanResponseModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'end_date': 'datetime',
        'plan_type': 'str'
    }

    attribute_map = {
        'end_date': 'endDate',
        'plan_type': 'planType'
    }

    def __init__(self, end_date=None, plan_type=None):  # noqa: E501
        """CustomerPlanResponseModel - a model defined in Swagger"""  # noqa: E501
        self._end_date = None
        self._plan_type = None
        self.discriminator = None
        if end_date is not None:
            self.end_date = end_date
        if plan_type is not None:
            self.plan_type = plan_type

    @property
    def end_date(self):
        """Gets the end_date of this CustomerPlanResponseModel.  # noqa: E501

        The end date of the plan.  # noqa: E501

        :return: The end_date of this CustomerPlanResponseModel.  # noqa: E501
        :rtype: datetime
        """
        return self._end_date

    @end_date.setter
    def end_date(self, end_date):
        """Sets the end_date of this CustomerPlanResponseModel.

        The end date of the plan.  # noqa: E501

        :param end_date: The end_date of this CustomerPlanResponseModel.  # noqa: E501
        :type: datetime
        """

        self._end_date = end_date

    @property
    def plan_type(self):
        """Gets the plan_type of this CustomerPlanResponseModel.  # noqa: E501

        The type of plan  # noqa: E501

        :return: The plan_type of this CustomerPlanResponseModel.  # noqa: E501
        :rtype: str
        """
        return self._plan_type

    @plan_type.setter
    def plan_type(self, plan_type):
        """Sets the plan_type of this CustomerPlanResponseModel.

        The type of plan  # noqa: E501

        :param plan_type: The plan_type of this CustomerPlanResponseModel.  # noqa: E501
        :type: str
        """
        allowed_values = ["Evaluation", "Paid", "Enterprise"]  # noqa: E501
        if plan_type not in allowed_values:
            raise ValueError(
                "Invalid value for `plan_type` ({0}), must be one of {1}"  # noqa: E501
                .format(plan_type, allowed_values)
            )

        self._plan_type = plan_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomerPlanResponseModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomerPlanResponseModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
