# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CustomerResponseModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'parent_id': 'str',
        'state': 'str',
        'signup_type': 'str',
        'disabled_date': 'datetime',
        'saas_customer_id': 'str',
        'plan': 'CustomerPlanResponseModel'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'parent_id': 'parentId',
        'state': 'state',
        'signup_type': 'signupType',
        'disabled_date': 'disabledDate',
        'saas_customer_id': 'saasCustomerId',
        'plan': 'plan'
    }

    def __init__(self, id=None, name=None, parent_id=None, state=None, signup_type=None, disabled_date=None, saas_customer_id=None, plan=None):  # noqa: E501
        """CustomerResponseModel - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._parent_id = None
        self._state = None
        self._signup_type = None
        self._disabled_date = None
        self._saas_customer_id = None
        self._plan = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if parent_id is not None:
            self.parent_id = parent_id
        if state is not None:
            self.state = state
        if signup_type is not None:
            self.signup_type = signup_type
        if disabled_date is not None:
            self.disabled_date = disabled_date
        if saas_customer_id is not None:
            self.saas_customer_id = saas_customer_id
        if plan is not None:
            self.plan = plan

    @property
    def id(self):
        """Gets the id of this CustomerResponseModel.  # noqa: E501

        The customer's ID. This property supports: filtering and searching.  # noqa: E501

        :return: The id of this CustomerResponseModel.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CustomerResponseModel.

        The customer's ID. This property supports: filtering and searching.  # noqa: E501

        :param id: The id of this CustomerResponseModel.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this CustomerResponseModel.  # noqa: E501

        The customer's name. This property supports: sorting, filtering and searching.  # noqa: E501

        :return: The name of this CustomerResponseModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CustomerResponseModel.

        The customer's name. This property supports: sorting, filtering and searching.  # noqa: E501

        :param name: The name of this CustomerResponseModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def parent_id(self):
        """Gets the parent_id of this CustomerResponseModel.  # noqa: E501

        The customer's parent ID if there is an L1/L2 relationship. This property supports: filtering.  # noqa: E501

        :return: The parent_id of this CustomerResponseModel.  # noqa: E501
        :rtype: str
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this CustomerResponseModel.

        The customer's parent ID if there is an L1/L2 relationship. This property supports: filtering.  # noqa: E501

        :param parent_id: The parent_id of this CustomerResponseModel.  # noqa: E501
        :type: str
        """

        self._parent_id = parent_id

    @property
    def state(self):
        """Gets the state of this CustomerResponseModel.  # noqa: E501

        The customer's current state.  # noqa: E501

        :return: The state of this CustomerResponseModel.  # noqa: E501
        :rtype: str
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this CustomerResponseModel.

        The customer's current state.  # noqa: E501

        :param state: The state of this CustomerResponseModel.  # noqa: E501
        :type: str
        """
        allowed_values = ["Pending", "Active", "Disabled"]  # noqa: E501
        if state not in allowed_values:
            raise ValueError(
                "Invalid value for `state` ({0}), must be one of {1}"  # noqa: E501
                .format(state, allowed_values)
            )

        self._state = state

    @property
    def signup_type(self):
        """Gets the signup_type of this CustomerResponseModel.  # noqa: E501

        The customer's signup type. This property supports: sorting.  # noqa: E501

        :return: The signup_type of this CustomerResponseModel.  # noqa: E501
        :rtype: str
        """
        return self._signup_type

    @signup_type.setter
    def signup_type(self, signup_type):
        """Sets the signup_type of this CustomerResponseModel.

        The customer's signup type. This property supports: sorting.  # noqa: E501

        :param signup_type: The signup_type of this CustomerResponseModel.  # noqa: E501
        :type: str
        """
        allowed_values = ["Standard", "AwsMarketplace", "TackleAws", "TackleAzure"]  # noqa: E501
        if signup_type not in allowed_values:
            raise ValueError(
                "Invalid value for `signup_type` ({0}), must be one of {1}"  # noqa: E501
                .format(signup_type, allowed_values)
            )

        self._signup_type = signup_type

    @property
    def disabled_date(self):
        """Gets the disabled_date of this CustomerResponseModel.  # noqa: E501

        The customer's disabled date. This property supports: filtering.  # noqa: E501

        :return: The disabled_date of this CustomerResponseModel.  # noqa: E501
        :rtype: datetime
        """
        return self._disabled_date

    @disabled_date.setter
    def disabled_date(self, disabled_date):
        """Sets the disabled_date of this CustomerResponseModel.

        The customer's disabled date. This property supports: filtering.  # noqa: E501

        :param disabled_date: The disabled_date of this CustomerResponseModel.  # noqa: E501
        :type: datetime
        """

        self._disabled_date = disabled_date

    @property
    def saas_customer_id(self):
        """Gets the saas_customer_id of this CustomerResponseModel.  # noqa: E501

        The customer's external Saas ID. This property supports: sorting.  # noqa: E501

        :return: The saas_customer_id of this CustomerResponseModel.  # noqa: E501
        :rtype: str
        """
        return self._saas_customer_id

    @saas_customer_id.setter
    def saas_customer_id(self, saas_customer_id):
        """Sets the saas_customer_id of this CustomerResponseModel.

        The customer's external Saas ID. This property supports: sorting.  # noqa: E501

        :param saas_customer_id: The saas_customer_id of this CustomerResponseModel.  # noqa: E501
        :type: str
        """

        self._saas_customer_id = saas_customer_id

    @property
    def plan(self):
        """Gets the plan of this CustomerResponseModel.  # noqa: E501


        :return: The plan of this CustomerResponseModel.  # noqa: E501
        :rtype: CustomerPlanResponseModel
        """
        return self._plan

    @plan.setter
    def plan(self, plan):
        """Sets the plan of this CustomerResponseModel.


        :param plan: The plan of this CustomerResponseModel.  # noqa: E501
        :type: CustomerPlanResponseModel
        """

        self._plan = plan

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CustomerResponseModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CustomerResponseModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
