# coding: utf-8

"""
    CloudCheckr API

    CloudCheckr API  # noqa: E501

    OpenAPI spec version: v1
    Contact: support@cloudcheckr.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LinkedAwsCommercialAccountModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'aws_account_id': 'str'
    }

    attribute_map = {
        'aws_account_id': 'awsAccountId'
    }

    def __init__(self, aws_account_id=None):  # noqa: E501
        """LinkedAwsCommercialAccountModel - a model defined in Swagger"""  # noqa: E501
        self._aws_account_id = None
        self.discriminator = None
        if aws_account_id is not None:
            self.aws_account_id = aws_account_id

    @property
    def aws_account_id(self):
        """Gets the aws_account_id of this LinkedAwsCommercialAccountModel.  # noqa: E501

        Commercial AWS account ID.  # noqa: E501

        :return: The aws_account_id of this LinkedAwsCommercialAccountModel.  # noqa: E501
        :rtype: str
        """
        return self._aws_account_id

    @aws_account_id.setter
    def aws_account_id(self, aws_account_id):
        """Sets the aws_account_id of this LinkedAwsCommercialAccountModel.

        Commercial AWS account ID.  # noqa: E501

        :param aws_account_id: The aws_account_id of this LinkedAwsCommercialAccountModel.  # noqa: E501
        :type: str
        """

        self._aws_account_id = aws_account_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LinkedAwsCommercialAccountModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LinkedAwsCommercialAccountModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
